name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "4f2534559b938e661168af847419a63e" # 这里改成你自己的 account_id
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "https://p.clash.id", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "e3bbc5207842431fbf36b4093558744e" },
]

[site]
bucket = "./static/dist"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'pastes'
